books/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from books import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', views.book_list, name='book_list'),
    url(r'^create/$', views.book_create, name='book_create'),
    url(r'^(?P<pk>\d+)/update/$', views.book_update, name='book_update'),
    url(r'^(?P<pk>\d+)/delete/$', views.book_delete, name='book_delete'),
]

category/urls.py
from django.conf.urls import url

from .views import (
	CategoryCreateView,
	CategoryListView,
	CategoryUpdateView,	
	CategoryDeleteView,	
	# CategoryDetailView,
)

urlpatterns = [    
    url(r'^$', CategoryListView.as_view(), name='list'),
    url(r'^create/$', CategoryCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', CategoryUpdateView.as_view(), name='detail'),
    url(r'^delete/(?P<pk>\d+)/$', CategoryDeleteView.as_view(), name='delete'),
    # url(r'^lists/(?P<pk>\d+)/$', CategoryDetailView.as_view(), name='details'),
    
]

xpenseapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView, LogoutView
from profiles.views import RegisterView

# from menus.views    import HomeView
# from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
# from restaurants.views import (
# 	restaurant_createview,
#     restaurant_listview,
# 	RestaurantListView,
# 	RestaurantDetailView,
# 	# restaurant_createview
#     RestaurantCreateView

# )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),  
    url(r'^books/', include('books.urls', namespace='books')), 
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^period/', include('period.urls', namespace='period')),
    url(r'^budget/', include('budget.urls', namespace='budget')),
    url(r'^expense/', include('expense.urls', namespace='expense')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^logoutmessage/$', TemplateView.as_view(template_name='logoutform.html'), name='logoutmessage'),
]

category/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

# from restaurants.models import RestaurantLocation

# Create your models here.
class Category(models.Model):
	INCOME = 'Income'
	EXPENSE = 'Expense'    
	CATEGORY_CHOICES = (
		(INCOME, 'Income'),
		(EXPENSE, 'Expense'),
	)

	#associations
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL)
	# category stuffs 
	name		= models.CharField(max_length=120)

	cattype = models.CharField(
		max_length=120,
		help_text='Input Expense / Income.',
		choices=CATEGORY_CHOICES,
		default=EXPENSE,
	)
	# cattype 	= models.CharField(max_length=120, help_text='Input Expense / Income.')

	timestamp	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)


	def __str__(self):
		return self.name + " - " + self.cattype

	# def get_absolute_url(self):
	# 	return reverse('category:list', kwargs={'pk': self.pk})

	def get_absolute_url(self):
		# return reverse('category:detail', kwargs={'pk': self.pk})
		return '/category/update/' + str(self.pk)

	def get_absolute_url_delete(self):
		return '/category/delete/' + str(self.pk)
		# '/Category/delete/' + self.pk
		# reverse('category:delete', kwargs={'pk': self.pk})

	def search(self, query): #RestaurantLocation.objects.all().search(query) #RestaurantLocation.objects.filter(something).search()
  		if query:
  			query = query.strip()
  			return self.filter(
				Q(name__icontains=query)|
				Q(cattype__icontains=query)
				).distinct()
  		return self

	class Meta:
		ordering = ['name','-updated']

category/forms.py
from django import forms

# from restaurants.models import RestaurantLocation

from django.conf import settings

from .models import Category

User = settings.AUTH_USER_MODEL

class CategoryForm(forms.ModelForm):

	name = forms.CharField(widget=forms.TextInput(
				attrs={
					'class' : 'form-control',
					'placeholder' : 'Enter name here',
				}
			))

	categ = [
			('Expense','Expense'),
			('Income','Income'),
		]
	cattype = forms.CharField(widget=forms.Select(
				attrs={
					'class' : 'form-control',
					# 'placeholder' : 'Enter Category Type (Expense/Income)',
				}, choices=categ
			))

	class Meta:
		model = Category
		fields = [
			 # 'user',
			'name',
			'cattype',

		]			

	def __init__(self, user=None, *args, **kwargs):
		#print(kwargs.pop('user'))
		print(user)
		# print(kwargs)
		super(CategoryForm, self).__init__(*args, **kwargs)
		# self.fields['user'].queryset = Category.objects.filter(user=user)#.exclude(item__isnull=False)
		# self.fields['period'].queryset = Period.objects.filter(user=user)# .exclude(item__isnull=False)
		# dropdown = [
		# 	'Expense',
		# 	'Income',
		# ]
		# self.fields['cattype'].queryset = dropdown

category/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from django.core.paginator import Paginator

# Create your views here.
from .forms import CategoryForm
from .models import Category


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    # paginate_by = 10
    def get_queryset(self):
        filter_val = self.request.GET.get('q', 'give-default-value')
        if filter_val:            
            mycategory = Category.objects.filter(user=self.request.user).filter(
                    Q(name__icontains=filter_val)|
                    Q(cattype__icontains=filter_val)
                    ).distinct()
            # user_list = User.objects.all()
            # paginator = Paginator(mycategory, 10)
            return mycategory
        else:
            mycategory = Category.objects.filter(user=self.request.user).filter().distinct()
            return mycategory

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', 'give-default-value')
        return context

class CategoryCreateView(LoginRequiredMixin, CreateView):
    template_name = 'category/detail-add.html'
    form_class = CategoryForm
    success_url = '/category/?q='

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(CategoryCreateView, self).form_valid(form)

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Category'
        return context

    def get_form_kwargs(self):
        kwargs = super(CategoryCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'category/detail-update.html'
    form_class = CategoryForm
    success_url = '/category/?q='

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Category'
        return context

    def get_form_kwargs(self):
        kwargs = super(CategoryUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'category/category_delete.html'
    form_class = CategoryForm
    success_url = '/category/?q='    

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryDeleteView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Delete Category'
        return context

    def get_form_kwargs(self):
        kwargs = super(CategoryDeleteView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

category/templates/category/Category_detail.html
{% extends "base.html" %}

{% block head_title %}{{ user.username }} | {{ block.super}}{% endblock head_title %}

{% block content %}
<h1>{{ user.username }}</h1>
<form class='form' method='GET' action='.'>
<input type='text' placeholder="Search.." name='q' value='{{ request.GET.q }}'>
<button class='btn btn-default' type='submit'>Search</button>
</form>
<hr/>
{% if locations %}
{% for rest in locations %}
    <div class='row'>
    <div class='col-sm-12'>
        <div class='thumbnail'> 
            <h4>{{ rest.title }}</h4>
            <p><a href='{{ request.path}}?q={{ rest.name }}'>{{ rest.name }}</a> | 
            <!-- <a href='{{ request.path}}?q= {{ rest.category }}'> {{ rest.category }}</a> -->
           
            </p>
            <p>
<!--             <ul>
                {% for item in rest.item_set.all %}
                    <li style='margin-bottom: 15px;'><b>{{ item.name }}</b><br/>
                        {% for ing in item.get_contents %}
                            <a href='{{ request.path}}?q={{ ing}}'>{{ ing}}</a>
                        {% endfor %}
                    </li>
                {% endfor %}
            </ul> -->
            </p>
        </div>
    </div>
    </div>

{% endfor %}

{% else %}
<p class='lead'>No Items Found</p>
{% endif %}

{% endblock %}

category/templates/category/category_delete.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.name }} | Delete Category | {{ block.super }}{% endblock head_title %}

{% block content %}
<br>
<br>
<br>
<form method="post">{% csrf_token %}
  <div class='container'>
    <div class='row'>
      <div class='col-3'>
      </div>
      <div class='col-6'>
        <div class="card">
          <div class="card-header">
          <h3>{{ title }}</h3>	          
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>
		Are you sure you want to delete "{{ object }}" ?
		<br></p>
		<button class="btn btn-warning" type="submit" value="Save" >
	    	Save
	    </button>

	    <button onclick="window.history.back();" class="btn btn-secondary" type="button">Cancel</button>
              <footer class="blockquote-footer">Joel Spolsky <cite title="Source Title">CEO and Co-founder Stock Overflow|LinkedIn</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
      <div class='col-3'>
      </div>
    </div>
  </div>
</form>
{% endblock %}

category/templates/category/category_details.html
{% extends "base.html" %}

{% block head_title %}Category | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- {{ user.username }} -->
<h1>My Category</h1><br>
<form class='form' method='GET' action='.'>
  <input type='text' placeholder="Search.." name='q' value='{{ request.GET.q }}'>
  <button class='btn btn-primary btn-sm' type='submit'>Search</button>
</form>
<br>
<a class="btn btn-warning btn-sm" href="{% url "category:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Category </a>
<ui>

	<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Delete</th>
      <!-- <th scope="col">Delete2</th> -->
    </tr>
  </thead>
  <tbody>
  	{% for obj in locations %}
    <tr>
      <th scope="row">{{ obj.pk }}</th>
      <td><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a></td>
      <td>{{ obj.cattype }}</td>
      <td><a class="btn btn-secondary btn-sm" href='{{ obj.get_absolute_url_delete }}'><i class="fa fa-trash" aria-hidden="true"></i></a></td>
    </tr>
    	{% empty %}

	{% endfor %}
 <!--   <script>
   var elm = document.getElementById('delete-object');
    var objectID = elm.getAttribute('data-object-id');
    var resultDiv = document.getElementById('result');
    elm.addEventListener('click', function() {
  
  var ask = confirm('r u sure?');
  if (ask && objectID) {
    var r = "Page will be redirected to </category/delete/" + objectID + "/>";
    resultDiv.textContent = r;
  } else {
    resultDiv.textContent = "User cancelled the dialog box...";
  }
  return false;
}); </script> -->
  </tbody>
</table>
<a class="btn btn-warning btn-sm" href="{% url "category:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Category </a>

</ui>
{% endblock %}

category/templates/category/category_list.html
{% extends "base.html" %}

{% block head_title %}Category | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- {{ user.username }} fas fa-search-->
<!-- <div class="container-fluid">
<h2>My Category</h2><br>
</div> -->
<!-- 
<form class='form' method='GET' action='.'>
  <input type='text' placeholder="Search.." name='q' value='{{ request.GET.q }}'>
  <button class='btn btn-warning btn-sm' type='submit'><i class="fas fa-search 2x" aria-hidden="true"></i> Search</button>
</form> -->
<br>
<br>
<br>
<div class="card">
  <h5 class="card-header">My Category</h5>
  <div class="card-body">
    <h5 class="card-title">
<div class="container-fluid">
  <form class='form' method='GET' action='.'>
      <div class="input-group mb-2">
            <div class="col-xs-4">
              <input type="text" class="form-control" 
              placeholder="Search.." aria-label="" aria-describedby="basic-addon1" name='q' value='{{ request.GET.q }}' id="ex3">
            </div>              
              <div class="input-group-prepend">
                  <button class="btn btn-outline-warning btn-sm" type="submit"><i class="fas fa-search 2a" aria-hidden="true"></i> Search</button>
              </div>
      </div>
  </form>
</div><hr></h5>
    <p class="card-text"><div class="container-fluid">
  <a class="btn btn-warning btn-sm" href="{% url "category:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Category </a>
</div></p>
    <div class="container-fluid">
  <table class="table table-hover border border-secondary table-sm">
  <thead class="thead-light" >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Delete</th>
      <!-- <th scope="col">Delete2</th> -->
    </tr>
  </thead>
  <tbody>
    {% for mycategory in object_list %}
    <tr>
      <th scope="row">{{ mycategory.pk }}</th>
      <td><a href='{{ mycategory.get_absolute_url }}'>{{ mycategory.name }}</a></td>
      <td>{{ mycategory.cattype }}</td>
      <td><a class="btn btn-secondary btn-sm" href='{{ mycategory.get_absolute_url_delete }}'><i class="fa fa-trash" aria-hidden="true"></i></a></td>
    </tr>
      {% empty %}

  {% endfor %}
 <!--   <script>
   var elm = document.getElementById('delete-object');
    var objectID = elm.getAttribute('data-object-id');
    var resultDiv = document.getElementById('result');
    elm.addEventListener('click', function() {
  
  var ask = confirm('r u sure?');
  if (ask && objectID) {
    var r = "Page will be redirected to </category/delete/" + objectID + "/>";
    resultDiv.textContent = r;
  } else {
    resultDiv.textContent = "User cancelled the dialog box...";
  }
  return false;
}); </script> -->
  </tbody>
</table>
</div>
<div class="container-fluid">
  <a class="btn btn-warning btn-sm" href="{% url "category:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Category </a>
</div>
  </div>
</div>
<br>
<br>
<br>
<br>
{% endblock %}

category/templates/category/detail-add.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- <h1>{{ title }}</h1> -->
{% include 'snippets/form-snippet.html' %}
{% endblock %}

category/templates/category/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.name }} | Category | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- <h1>{{form.instance.name}}</h1>

	<hr\>
	<h3>{{ title }}</h3> -->
	{% include 'snippets/form-snippet.html' with form=form %}
{% endblock %}