books/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from books import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', views.book_list, name='book_list'),
    url(r'^create/$', views.book_create, name='book_create'),
    url(r'^(?P<pk>\d+)/update/$', views.book_update, name='book_update'),
    url(r'^(?P<pk>\d+)/delete/$', views.book_delete, name='book_delete'),
]

period/urls.py
from django.conf.urls import url

from .views import (
	PeriodCreateView,
	PeriodListView,
	PeriodUpdateView,	
	PeriodDeleteView,	
)
# app_name = 'period'
urlpatterns = [    
    url(r'^$', PeriodListView.as_view(), name='list'),
    url(r'^create/$', PeriodCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', PeriodUpdateView.as_view(), name='detail'),
    url(r'^delete/(?P<pk>\d+)/$', PeriodDeleteView.as_view(), name='delete'),

    
]

xpenseapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView, LogoutView
from profiles.views import RegisterView

# from menus.views    import HomeView
# from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
# from restaurants.views import (
# 	restaurant_createview,
#     restaurant_listview,
# 	RestaurantListView,
# 	RestaurantDetailView,
# 	# restaurant_createview
#     RestaurantCreateView

# )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),  
    url(r'^books/', include('books.urls', namespace='books')), 
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^period/', include('period.urls', namespace='period')),
    url(r'^budget/', include('budget.urls', namespace='budget')),
    url(r'^expense/', include('expense.urls', namespace='expense')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^logoutmessage/$', TemplateView.as_view(template_name='logoutform.html'), name='logoutmessage'),
]

period/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Period(models.Model):

	#associations
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL)
	# period stuffs 
	perioddesc		= models.CharField(max_length=120)
	startdate		= models.DateField()
	enddate		= models.DateField()

	timestamp	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.perioddesc 

	def get_absolute_url(self):
		# return reverse('category:detail', kwargs={'pk': self.pk})
		return '/period/update/' + str(self.pk)

	def get_absolute_url_delete(self):
		return '/period/delete/' + str(self.pk)

	class Meta:
		ordering = ['perioddesc','-updated']

period/forms.py
from django import forms

# from restaurants.models import RestaurantLocation

from django.conf import settings

from .models import Period

User = settings.AUTH_USER_MODEL

class PeriodForm(forms.ModelForm):

	perioddesc = forms.CharField(widget=forms.TextInput(
				attrs={
					'class' : 'form-control',
					'placeholder' : 'Enter name here',
				}
			))

	# startdate = forms.DateField(
 #        widget=DateTimePicker(options={"format": "YYYY-MM-DD",
 #                                       "pickTime": False})),

	startdate = forms.DateField(widget=forms.TextInput(
				attrs={
					'class' : 'form-control',
					'placeholder' : 'Enter start date here',
					'type' : 'Date',
				}
			))
	enddate = forms.DateField(widget=forms.TextInput(
				attrs={
					'class' : 'form-control',
					'placeholder' : 'Enter end date here',
					'type' : 'Date',					
				}
			))

	class Meta:
		model = Period
		fields = [
			'perioddesc',
			'startdate',
			'enddate',
		]			

	def __init__(self, user=None, *args, **kwargs):
		print(user)
		super(PeriodForm, self).__init__(*args, **kwargs)
		# self.fields['period'].queryset = Period.objects.filter(user=user)# .exclude(item__isnull=False)
		self.fields['perioddesc'].label = "Period Description"
		self.fields['startdate'].label = "Start Date"
		self.fields['enddate'].label = "End Date"

period/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q

# Create your views here.
from .forms import PeriodForm
from .models import Period

# class PeriodListView(LoginRequiredMixin, ListView):
# 	def get_queryset(self):
# 		return Period.objects.filter(user=self.request.user)
class PeriodListView(LoginRequiredMixin, ListView):
    model = Period
    def get_queryset(self):
        filter_val = self.request.GET.get('q', 'give-default-value')
        if filter_val:            
            myperiod = Period.objects.fileter(user=self.request.user).filter(
                    Q(perioddesc__icontains=filter_val)
                    ).distinct()
            return myperiod
        else:
            myperiod = Period.objects.filter(user=self.request.user).filter().distinct()
            return myperiod

    def get_context_data(self, **kwargs):
        context = super(PeriodListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', 'give-default-value')
        return context


class PeriodCreateView(LoginRequiredMixin, CreateView):
    template_name = 'Period/detail-add.html'
    form_class = PeriodForm
    success_url = '/period/?q='

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(PeriodCreateView, self).form_valid(form)

    def get_queryset(self):
        return Period.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(PeriodCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Period'
        return context

    def get_form_kwargs(self):
        kwargs = super(PeriodCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class PeriodUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'Period/detail-update.html'
    form_class = PeriodForm
    success_url = '/period/?q='

    def get_queryset(self):
        return Period.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(PeriodUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Period'
        return context

    def get_form_kwargs(self):
        kwargs = super(PeriodUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class PeriodDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'Period/Period_delete.html'
    form_class = PeriodForm
    success_url = '/period/?q='    

    def get_queryset(self):
        return Period.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(PeriodDeleteView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Delete Period'
        return context

    def get_form_kwargs(self):
        kwargs = super(PeriodDeleteView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

period/templates/period/detail-add.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- <h1>{{ title }}</h1> -->
{% include 'snippets/form-snippet.html' %}
{% endblock %}

period/templates/period/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.name }} | Category | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- <h1>{{form.instance.name}}</h1>

	<hr\>
	<h3>{{ title }}</h3> -->
	{% include 'snippets/form-snippet.html' with form=form %}
{% endblock %}

period/templates/period/period_delete.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.name }} | Delete Period | {{ block.super }}{% endblock head_title %}

{% block content %}
<br>
<br>
<br>
<form method="post">{% csrf_token %}
  <div class='container'>
    <div class='row'>
      <div class='col-3'>
      </div>
      <div class='col-6'>
        <div class="card">
          <div class="card-header">
          <h3>{{ title }}</h3>	          
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>
		Are you sure you want to delete "{{ object }}" ?
		<br></p>
		<button class="btn btn-warning" type="submit" value="Save" >
	    	Save
	    </button>

	    <button onclick="window.history.back();" class="btn btn-secondary" type="button">Cancel</button>
              <footer class="blockquote-footer">Joel Spolsky <cite title="Source Title">CEO and Co-founder Stock Overflow|LinkedIn</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
      <div class='col-3'>
      </div>
    </div>
  </div>
</form>
{% endblock %}

period/templates/period/period_list.html
{% extends "base.html" %}

{% block head_title %}Period | {{ block.super }}{% endblock head_title %}

{% block content %}
<br>
<br>
<br>
<div class="card">
  <h5 class="card-header">My Period</h5>
  <div class="card-body">
    <h5 class="card-title">
<div class="container-fluid">
  <form class='form' method='GET' action='.'>
      <div class="input-group mb-2">
            <div class="col-xs-4">
              <input type="text" class="form-control" 
              placeholder="Search.." aria-label="" aria-describedby="basic-addon1" name='q' value='{{ request.GET.q }}' id="ex3">
            </div>              
              <div class="input-group-prepend">
                  <button class="btn btn-outline-warning btn-sm" type="submit"><i class="fas fa-search 2a" aria-hidden="true"></i> Search</button>
              </div>
      </div>
  </form>
</div><hr></h5>
    <p class="card-text"><div class="container-fluid">
  <a class="btn btn-warning btn-sm" href="{% url "period:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Period </a>
</div></p>
    <div class="container-fluid">
  <table class="table table-hover border border-secondary table-sm">
  <thead class="thead-light" >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Period Desc</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for myperiod in object_list %}
    <tr>
      <th scope="row">{{ myperiod.pk }}</th>
      <td><a href='{{ myperiod.get_absolute_url }}'>{{ myperiod.perioddesc }}</a></td>
      <td>{{ myperiod.startdate }}</td>
      <td>{{ myperiod.enddate }}</td>
            <td><a class="btn btn-secondary btn-sm" href='{{ myperiod.get_absolute_url_delete }}'><i class="fa fa-trash" aria-hidden="true"></i></a></td>
    </tr>
      {% empty %}

  {% endfor %}

  </tbody>
</table>
</div>
<div class="container-fluid">
  <a class="btn btn-warning btn-sm" href="{% url "period:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Period </a>
</div>
  </div>
</div>


<br>
<br>
<br>
<br>
{% endblock %}

period/templates/period/xperiod_list.html
{% extends "base.html" %}

{% block head_title %}Period | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>My Period</h1><br>
<a class="btn btn-warning btn-sm" href="{% url "period:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Period </a>
<ui>

	<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Period Desc</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  	{% for obj in object_list %}
    <tr>
      <th scope="row">{{ obj.pk }}</th>
      <td><a href='{{ obj.get_absolute_url }}'>{{ obj.perioddesc }}</a></td>
      <td>{{ obj.startdate }}</td>
      <td>{{ obj.enddate }}</td>
      <!-- <td><a class="btn btn-secondary btn-sm" href='{{ obj.get_absolute_url_delete }}' role="button">delete</a></td> -->
            <td><a class="btn btn-secondary btn-sm" href='{{ obj.get_absolute_url_delete }}'><i class="fa fa-trash" aria-hidden="true"></i></a></td>
    </tr>
    	{% empty %}

	{% endfor %}
   
  </tbody>
</table>
<a class="btn btn-warning btn-sm" href="{% url "period:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Period </a>

</ui>
{% endblock %}