books/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from books import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', views.book_list, name='book_list'),
    url(r'^create/$', views.book_create, name='book_create'),
    url(r'^(?P<pk>\d+)/update/$', views.book_update, name='book_update'),
    url(r'^(?P<pk>\d+)/delete/$', views.book_delete, name='book_delete'),
]

expense/urls.py
from django.conf.urls import url

from .views import (
	ExpenseCreateView,
	ExpenseListView,
	ExpenseUpdateView,	
	ExpenseDeleteView,	
)

urlpatterns = [    
    url(r'^$', ExpenseListView.as_view(), name='list'),
    url(r'^create/$', ExpenseCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', ExpenseUpdateView.as_view(), name='detail'),
    url(r'^delete/(?P<pk>\d+)/$', ExpenseDeleteView.as_view(), name='delete'),
]

xpenseapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView, LogoutView
from profiles.views import RegisterView

# from menus.views    import HomeView
# from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
# from restaurants.views import (
# 	restaurant_createview,
#     restaurant_listview,
# 	RestaurantListView,
# 	RestaurantDetailView,
# 	# restaurant_createview
#     RestaurantCreateView

# )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),  
    url(r'^books/', include('books.urls', namespace='books')), 
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^period/', include('period.urls', namespace='period')),
    url(r'^budget/', include('budget.urls', namespace='budget')),
    url(r'^expense/', include('expense.urls', namespace='expense')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^logoutmessage/$', TemplateView.as_view(template_name='logoutform.html'), name='logoutmessage'),
]

expense/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from category.models import Category

# Create your models here.
class Expense(models.Model):

	#associations
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL)
	category	= models.ForeignKey(Category,null=True,on_delete=models.SET_NULL,)

	# period stuffs 
	expensedate		= models.DateField()
	amount		= models.DecimalField(max_digits=16, decimal_places=2, blank=False, null=False)
	remarks		= models.TextField(blank=True, null=True, max_length=120, help_text='Enter Remarks here')

	timestamp	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)

	# def __str__(self):
	# 	return self.category 

	def get_absolute_url(self):
		# return reverse('category:detail', kwargs={'pk': self.pk})
		return '/expense/update/' + str(self.pk)

	def get_absolute_url_delete(self):
		return '/expense/delete/' + str(self.pk)

	class Meta:
		ordering = ['-expensedate','category','-updated']

expense/forms.py
from django import forms
from django.conf import settings

from category.models import Category
from .models import Expense

User = settings.AUTH_USER_MODEL

class ExpenseForm(forms.ModelForm):


	expensedate = forms.DateField(widget=forms.DateInput(
				attrs={
					'class' : 'form-control',
					'placeholder' : 'Enter expense date here..',
					'label' : 'Expense Date',
					'type' : 'Date',
				}
			))
	amount = forms.DecimalField(widget=forms.TextInput(
				attrs={
					'class' : 'form-control',
					'placeholder' : 'Enter amount here...',
				}
			))

	remarks = forms.CharField(widget=forms.TextInput(
				attrs={
					'class' : 'form-control',
					'placeholder' : 'Enter remarks here...',
				}
			))

	# source = forms.CharField(       # A hidden input for internal use
	# 	max_length=50,              # tell from which page the user sent the message
	# 	widget=forms.HiddenInput()
	# )


	class Meta:
		model = Expense
		fields = [
			'category',
			'expensedate',
			'amount',
			'remarks',
		]			



	def clean(self):
		cleaned_data = super(ExpenseForm, self).clean()
		expensedate = cleaned_data.get('expensedate')
		amount = cleaned_data.get('amount')
		remarks = cleaned_data.get('remarks')
		if not expensedate and not amount and not remarks:
			raise forms.ValidationError('You have to write something!')

	def __init__(self, user=None, *args, **kwargs):
		print(user)
		super(ExpenseForm, self).__init__(*args, **kwargs)
		self.fields['category'].queryset = Category.objects.filter(user=user)# .exclude(item__isnull=False)
		self.fields['expensedate'].label = "Expense Date"

expense/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from django.shortcuts import render

# Create your views here.
from .forms import ExpenseForm
from .models import Expense

# class ExpenseListView(LoginRequiredMixin, ListView):
# 	def get_queryset(self):
# 		return Expense.objects.filter(user=self.request.user)
class ExpenseListView(LoginRequiredMixin, ListView):
    model = Expense
    def get_queryset(self):
        filter_val = self.request.GET.get('q', 'give-default-value')
        if filter_val:            
            myexpense = Expense.objects.filter(user=self.request.user).filter(
                    Q(remarks__icontains=filter_val)|
                    Q(category__name__icontains=filter_val)|
                    Q(category__name__iexact=filter_val)|
                    Q(category__cattype__iexact=filter_val)|
                    Q(category__cattype__icontains=filter_val)
                    ).distinct()
            return myexpense
        else:
            myexpense = Expense.objects.filter(user=self.request.user).filter().distinct()
            return myexpense

    def get_context_data(self, **kwargs):
        context = super(ExpenseListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', 'give-default-value')
        return context


class ExpenseCreateView(LoginRequiredMixin, CreateView):
    template_name = 'expense/detail-add.html'
    form_class = ExpenseForm
    success_url = '/expense/?q='

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ExpenseCreateView, self).form_valid(form)

    def get_queryset(self):
        return Period.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ExpenseCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Expense'
        return context

    def get_form_kwargs(self):
        kwargs = super(ExpenseCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

# def home(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             pass  # does nothing, just trigger the validation
#     else:
#         form = ContactForm()
#     return render(request, 'home.html', {'form': form})

class ExpenseUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'Expense/detail-update.html'
    form_class = ExpenseForm
    success_url = '/expense/?q='

    def get_queryset(self):
        return Expense.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ExpenseUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Expense'
        return context

    def get_form_kwargs(self):
        kwargs = super(ExpenseUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class ExpenseDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'Expense/expense_delete.html'
    form_class = ExpenseForm
    success_url = '/expense/?q='    

    def get_queryset(self):
        return Expense.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ExpenseDeleteView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Delete Expense'
        return context

    def get_form_kwargs(self):
        kwargs = super(ExpenseDeleteView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

expense/templates/expense/detail-add.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- <h1>{{ title }}</h1> -->
{% include 'snippets/form-snippet.html' %}

{% endblock %}

expense/templates/expense/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.name }} | Expense | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- <h1>{{form.instance.name}}</h1>

	<hr\>
	<h3>{{ title }}</h3> -->
	{% include 'snippets/form-snippet.html' with form=form %}
{% endblock %}

expense/templates/expense/expense_delete.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.name }} | Delete Period | {{ block.super }}{% endblock head_title %}

{% block content %}
<!-- <h1>{{form.instance.name}}</h1>

	<hr\>
	<h3>{{ title }}</h3>	
	<form method="post">{% csrf_token %}
		<br>
		Are you sure you want to delete "{{ object.category }}" ?
		<br>
		<br>
	    <button class="btn btn-warning" type="submit" value="Save" >
	    	Save
	    </button>

	    <button onclick="window.history.back();" class="btn btn-secondary" type="button">Cancel</button>
    </form>


    <br>
<br> -->
<br>
<br>
<br>
<form method="post">{% csrf_token %}
  <div class='container'>
    <div class='row'>
      <div class='col-3'>
      </div>
      <div class='col-6'>
        <div class="card">
          <div class="card-header">
          <h3>{{ title }}</h3>	          
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>
		Are you sure you want to delete "{{ object.category }}" ?
		<br></p>
		<button class="btn btn-warning" type="submit" value="Save" >
	    	Save
	    </button>

	    <button onclick="window.history.back();" class="btn btn-secondary" type="button">Cancel</button>
              <footer class="blockquote-footer">Joel Spolsky <cite title="Source Title">CEO and Co-founder Stock Overflow|LinkedIn</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
      <div class='col-3'>
      </div>
    </div>
  </div>
</form>

{% endblock %}

expense/templates/expense/expense_list.html
{% extends "base.html" %}

{% block head_title %}Expense | {{ block.super }}{% endblock head_title %}

{% block content %}
<br>
<br>
<br>
<div class="card">
  <h5 class="card-header">My Expense</h5>
  <div class="card-body">
    <h5 class="card-title">
<div class="container-fluid">
  <form class='form' method='GET' action='.'>
      <div class="input-group mb-2">
            <div class="col-xs-4">
              <input type="text" class="form-control" 
              placeholder="Search.." aria-label="" aria-describedby="basic-addon1" name='q' value='{{ request.GET.q }}' id="ex3">
            </div>              
              <div class="input-group-prepend">
                  <button class="btn btn-outline-warning btn-sm" type="submit"><i class="fas fa-search 2a" aria-hidden="true"></i> Search</button>
              </div>
      </div>
  </form>
</div><hr></h5>
    <p class="card-text"><div class="container-fluid">
  <a class="btn btn-warning btn-sm" href="{% url "expense:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Expense </a>
</div></p>
    <div class="container-fluid">
  <table class="table table-hover border border-secondary table-sm">
  <thead class="thead-light" >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Category</th>
      <th scope="col">Expense Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Remarks</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for myexpense in object_list %}
    <tr>
      <th scope="row">{{ myexpense.pk }}</th>
      <td><a href='{{ myexpense.get_absolute_url }}'>{{ myexpense.category }}</a></td>
      <td>{{ myexpense.expensedate }}</td>
      <td>{{ myexpense.amount }}</td>
      <td>{{ myexpense.remarks }}</td>
            <td><a class="btn btn-secondary btn-sm" href='{{ myexpense.get_absolute_url_delete }}'><i class="fa fa-trash" aria-hidden="true"></i></a></td>
    </tr>
      {% empty %}

  {% endfor %}

  </tbody>
</table>
</div>
<div class="container-fluid">
  <a class="btn btn-warning btn-sm" href="{% url "expense:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Expense </a>
</div>
  </div>
</div>


<br>
<br>
<br>
<br>
{% endblock %}

expense/templates/expense/xexpense_list.html
{% extends "base.html" %}

{% block head_title %}Expense | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>My Expense</h1><br>
<a class="btn btn-warning btn-sm" href="{% url "expense:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Expense </a>
<ui>

	<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Category</th>
      <th scope="col">Expense Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Remarks</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  	{% for obj in object_list %}
    <tr>
      <th scope="row">{{ obj.pk }}</th>
      <td><a href='{{ obj.get_absolute_url }}'>{{ obj.category }}</a></td>
      <td>{{ obj.expensedate }}</td>
      <td>{{ obj.amount }}</td>
      <td>{{ obj.remarks }}</td>
      <!-- <td><a class="btn btn-secondary btn-sm" href='{{ obj.get_absolute_url_delete }}' role="button">delete</a></td> -->
            <td><a class="btn btn-secondary btn-sm" href='{{ obj.get_absolute_url_delete }}'><i class="fa fa-trash" aria-hidden="true"></i></a></td>
    </tr>
    	{% empty %}

	{% endfor %}
   
  </tbody>
</table>
<a class="btn btn-warning btn-sm" href="{% url "expense:create" %}" role="button"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Expense </a>

</ui>
{% endblock %}